Chore: 배포 도중 예외 사항 처리 및 도커 유저네임 환경변수 파일에 추가 #37

diff --git a/.github/workflows/reacton-ci-cd.yml b/.github/workflows/reacton-ci-cd.yml
--- a/.github/workflows/reacton-ci-cd.yml
+++ b/.github/workflows/reacton-ci-cd.yml
@@ -71,7 +71,14 @@ jobs:
             echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
             echo "SPRING_JPA_HIBERNATE_DDL_AUTO=update" >> .env
             echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
-            sudo docker-compose pull
-            sudo docker-compose up -d --remove-orphans
+            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME}}" >> .env
+            cat .env
+            echo "🔄 Pulling latest Docker images..."
+            sudo docker-compose pull || { echo "❌ Failed to pull Docker images"; exit 1; }
+            echo "🚀 Running Docker containers..."
+            sudo docker-compose up -d --remove-orphans || { echo "❌ Failed to start containers"; exit 1; }
+            echo "🧹 Cleaning up..."
             rm -f .env
-            sudo docker image prune -f
+            sudo docker image prune -f || { echo "❌ Failed to prune Docker images"; exit 1; }
+            echo "✅ Deployment completed successfully!"
+        
